name: CI

on: 
  pull_request:
  branches: [ "main" ]

  jobs:
    build-and-test:

      runs-on: macos-14

      timeout-minutes: 8

      steps:
        - uses: actions:/checkout@v4

        -name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode15.3.app

        -name: Xcode version
        run: /usr/bin/xocodebuild -version

        -name: Buid and Test
        run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES