name: CI_iOS

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-14

    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Build and Test
      run: xcodebuild clean build test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=17.4,name=iPhone 15 Pro" ONLY_ACTIVE_ARCH=YES
